import type { NormalizedModel, ModelSource } from '@/lib/types';
import { getLicense } from '@/lib/licenses';

const SOURCES: Record<string, ModelSource> = {
  thingiverse: {
    id: 'src-thingiverse',
    name: 'thingiverse',
    displayName: 'Thingiverse',
    baseUrl: 'https://www.thingiverse.com',
    attributionRequired: true,
  },
  printables: {
    id: 'src-printables',
    name: 'printables',
    displayName: 'Printables',
    baseUrl: 'https://www.printables.com',
    attributionRequired: true,
  },
  myminifactory: {
    id: 'src-myminifactory',
    name: 'myminifactory',
    displayName: 'MyMiniFactory',
    baseUrl: 'https://www.myminifactory.com',
    attributionRequired: true,
  },
};

export const MOCK_MODELS: NormalizedModel[] = [
  {
    id: 'mdl-001',
    externalId: 'tv-482910',
    name: 'Geometric Desk Organizer',
    localizedName: 'מארגן שולחן גיאומטרי',
    description: 'A modular geometric desk organizer with separate compartments for pens, cards, and small items.',
    localizedDescription: 'מארגן שולחן מודולרי בעיצוב גיאומטרי עם תאים נפרדים לעטים, כרטיסים ופריטים קטנים.',
    images: [
      { url: '/mock/models/desk-organizer-1.jpg', alt: 'Geometric desk organizer front view', isThumbnail: true, cachedUrl: '/mock/models/desk-organizer-1.jpg' },
      { url: '/mock/models/desk-organizer-2.jpg', alt: 'Geometric desk organizer side view', isThumbnail: false },
    ],
    source: SOURCES.thingiverse,
    sourceUrl: 'https://www.thingiverse.com/thing:482910',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-office'],
    tags: ['organizer', 'desk', 'geometric', 'modular', 'office'],
    popularityScore: 87,
    supportsEmbossedText: true,
    supportedMaterials: ['PLA', 'PETG', 'ABS'],
    defaultDimensions: { widthMm: 150, heightMm: 100, depthMm: 120 },
    minDimensions: { widthMm: 75, heightMm: 50, depthMm: 60 },
    maxDimensions: { widthMm: 300, heightMm: 200, depthMm: 240 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 45,
    printTimeMinutes: 180,
    createdAt: '2024-06-15T10:00:00Z',
    updatedAt: '2025-01-20T08:00:00Z',
    indexedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'mdl-002',
    externalId: 'pr-119283',
    name: 'Dragon Figurine - Articulated',
    localizedName: 'דמות דרקון מפרקית',
    description: 'Fully articulated dragon figurine with movable joints. Print-in-place design, no assembly required.',
    localizedDescription: 'דמות דרקון מפרקית עם מפרקים זזים. עיצוב הדפסה במקום, ללא צורך בהרכבה.',
    images: [
      { url: '/mock/models/dragon-1.jpg', alt: 'Articulated dragon front', isThumbnail: true, cachedUrl: '/mock/models/dragon-1.jpg' },
      { url: '/mock/models/dragon-2.jpg', alt: 'Articulated dragon detail', isThumbnail: false },
    ],
    source: SOURCES.printables,
    sourceUrl: 'https://www.printables.com/model/119283',
    license: getLicense('CC-BY-SA-4.0'),
    categories: ['cat-toys', 'cat-miniatures'],
    tags: ['dragon', 'articulated', 'figurine', 'print-in-place', 'fantasy'],
    popularityScore: 95,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA', 'PETG'],
    defaultDimensions: { widthMm: 200, heightMm: 80, depthMm: 60 },
    minDimensions: { widthMm: 100, heightMm: 40, depthMm: 30 },
    maxDimensions: { widthMm: 400, heightMm: 160, depthMm: 120 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 55,
    printTimeMinutes: 240,
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2025-02-15T08:00:00Z',
    indexedAt: '2025-02-20T00:00:00Z',
  },
  {
    id: 'mdl-003',
    externalId: 'tv-553201',
    name: 'Lithophane Photo Frame',
    localizedName: 'מסגרת תמונה ליתופיין',
    description: 'Custom lithophane photo frame with built-in LED holder. Upload your photo to create a unique glowing display.',
    localizedDescription: 'מסגרת תמונה ליתופיין מותאמת אישית עם מחזיק LED מובנה. העלו את התמונה שלכם ליצירת תצוגה זוהרת ייחודית.',
    images: [
      { url: '/mock/models/lithophane-1.jpg', alt: 'Lithophane frame lit', isThumbnail: true, cachedUrl: '/mock/models/lithophane-1.jpg' },
    ],
    source: SOURCES.thingiverse,
    sourceUrl: 'https://www.thingiverse.com/thing:553201',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-home-decor', 'cat-gifts'],
    tags: ['lithophane', 'photo', 'frame', 'LED', 'gift', 'personalized'],
    popularityScore: 78,
    supportsEmbossedText: true,
    supportedMaterials: ['PLA'],
    defaultDimensions: { widthMm: 130, heightMm: 180, depthMm: 30 },
    minDimensions: { widthMm: 80, heightMm: 110, depthMm: 20 },
    maxDimensions: { widthMm: 200, heightMm: 280, depthMm: 40 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 35,
    printTimeMinutes: 300,
    createdAt: '2024-08-20T10:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
    indexedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'mdl-004',
    externalId: 'mmf-78412',
    name: 'Flexi Rex - Flexible T-Rex',
    localizedName: 'פלקסי רקס - טירנוזאורוס גמיש',
    description: 'Print-in-place flexible T-Rex toy. A fun fidget-friendly dinosaur with smooth articulation.',
    localizedDescription: 'צעצוע טירנוזאורוס גמיש להדפסה במקום. דינוזאור כיפי עם תנועה חלקה, מושלם לפידג\'ט.',
    images: [
      { url: '/mock/models/flexi-rex-1.jpg', alt: 'Flexi Rex colorful', isThumbnail: true, cachedUrl: '/mock/models/flexi-rex-1.jpg' },
    ],
    source: SOURCES.myminifactory,
    sourceUrl: 'https://www.myminifactory.com/object/78412',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-toys'],
    tags: ['dinosaur', 'flexible', 'fidget', 'trex', 'articulated', 'kids'],
    popularityScore: 92,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA', 'TPU'],
    defaultDimensions: { widthMm: 180, heightMm: 70, depthMm: 50 },
    minDimensions: { widthMm: 90, heightMm: 35, depthMm: 25 },
    maxDimensions: { widthMm: 360, heightMm: 140, depthMm: 100 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 30,
    printTimeMinutes: 120,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2025-03-01T08:00:00Z',
    indexedAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'mdl-005',
    externalId: 'pr-201445',
    name: 'Minimalist Wall Clock',
    localizedName: 'שעון קיר מינימליסטי',
    description: 'Modern minimalist wall clock with clean number design. Requires a standard clock mechanism (not included).',
    localizedDescription: 'שעון קיר מודרני בעיצוב מינימליסטי עם מספרים נקיים. דורש מנגנון שעון סטנדרטי (לא כלול).',
    images: [
      { url: '/mock/models/wall-clock-1.jpg', alt: 'Minimalist wall clock', isThumbnail: true, cachedUrl: '/mock/models/wall-clock-1.jpg' },
    ],
    source: SOURCES.printables,
    sourceUrl: 'https://www.printables.com/model/201445',
    license: getLicense('CC-BY-SA-4.0'),
    categories: ['cat-home-decor'],
    tags: ['clock', 'wall', 'minimalist', 'modern', 'home'],
    popularityScore: 71,
    supportsEmbossedText: true,
    supportedMaterials: ['PLA', 'PETG'],
    defaultDimensions: { widthMm: 250, heightMm: 250, depthMm: 25 },
    minDimensions: { widthMm: 150, heightMm: 150, depthMm: 15 },
    maxDimensions: { widthMm: 350, heightMm: 350, depthMm: 35 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 50,
    printTimeMinutes: 360,
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2025-02-10T08:00:00Z',
    indexedAt: '2025-02-15T00:00:00Z',
  },
  {
    id: 'mdl-006',
    externalId: 'tv-621890',
    name: 'Headphone Stand - Wave Design',
    localizedName: 'מעמד אוזניות - עיצוב גלי',
    description: 'Elegant headphone stand with flowing wave design. Sturdy base with cable management channel.',
    localizedDescription: 'מעמד אוזניות אלגנטי בעיצוב גלי זורם. בסיס יציב עם ערוץ לניהול כבלים.',
    images: [
      { url: '/mock/models/headphone-stand-1.jpg', alt: 'Headphone stand wave', isThumbnail: true, cachedUrl: '/mock/models/headphone-stand-1.jpg' },
    ],
    source: SOURCES.thingiverse,
    sourceUrl: 'https://www.thingiverse.com/thing:621890',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-gadgets', 'cat-office'],
    tags: ['headphone', 'stand', 'wave', 'desk', 'audio', 'cable management'],
    popularityScore: 83,
    supportsEmbossedText: true,
    supportedMaterials: ['PLA', 'PETG', 'ABS'],
    defaultDimensions: { widthMm: 120, heightMm: 250, depthMm: 120 },
    minDimensions: { widthMm: 80, heightMm: 170, depthMm: 80 },
    maxDimensions: { widthMm: 180, heightMm: 350, depthMm: 180 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 40,
    printTimeMinutes: 210,
    createdAt: '2024-07-12T10:00:00Z',
    updatedAt: '2025-01-25T08:00:00Z',
    indexedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'mdl-007',
    externalId: 'pr-330122',
    name: 'Planetary Gear Set',
    localizedName: 'סט גלגלי שיניים פלנטריים',
    description: 'Fully functional planetary gear mechanism. Great for education or desk fidget toy.',
    localizedDescription: 'מנגנון גלגלי שיניים פלנטריים פונקציונלי לחלוטין. מצוין ללמידה או כצעצוע פידג\'ט.',
    images: [
      { url: '/mock/models/planetary-gear-1.jpg', alt: 'Planetary gear set', isThumbnail: true, cachedUrl: '/mock/models/planetary-gear-1.jpg' },
    ],
    source: SOURCES.printables,
    sourceUrl: 'https://www.printables.com/model/330122',
    license: getLicense('CC0-1.0'),
    categories: ['cat-mechanical', 'cat-education'],
    tags: ['gear', 'planetary', 'mechanical', 'engineering', 'fidget', 'educational'],
    popularityScore: 76,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA', 'PETG'],
    defaultDimensions: { widthMm: 80, heightMm: 40, depthMm: 80 },
    minDimensions: { widthMm: 60, heightMm: 30, depthMm: 60 },
    maxDimensions: { widthMm: 160, heightMm: 80, depthMm: 160 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 25,
    printTimeMinutes: 90,
    createdAt: '2024-11-03T10:00:00Z',
    updatedAt: '2025-02-20T08:00:00Z',
    indexedAt: '2025-02-25T00:00:00Z',
  },
  {
    id: 'mdl-008',
    externalId: 'mmf-91230',
    name: 'Geometric Succulent Planter',
    localizedName: 'עציץ סוקולנטים גיאומטרי',
    description: 'Low-poly geometric planter perfect for succulents and small plants. Includes drainage hole.',
    localizedDescription: 'עציץ גיאומטרי בסגנון לו-פולי, מושלם לסוקולנטים וצמחים קטנים. כולל חור ניקוז.',
    images: [
      { url: '/mock/models/planter-1.jpg', alt: 'Geometric planter', isThumbnail: true, cachedUrl: '/mock/models/planter-1.jpg' },
    ],
    source: SOURCES.myminifactory,
    sourceUrl: 'https://www.myminifactory.com/object/91230',
    license: getLicense('CC-BY-SA-4.0'),
    categories: ['cat-home-decor'],
    tags: ['planter', 'succulent', 'geometric', 'low-poly', 'garden', 'plant'],
    popularityScore: 85,
    supportsEmbossedText: true,
    supportedMaterials: ['PLA', 'PETG'],
    defaultDimensions: { widthMm: 100, heightMm: 80, depthMm: 100 },
    minDimensions: { widthMm: 60, heightMm: 50, depthMm: 60 },
    maxDimensions: { widthMm: 200, heightMm: 160, depthMm: 200 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 28,
    printTimeMinutes: 150,
    createdAt: '2024-05-22T10:00:00Z',
    updatedAt: '2025-01-30T08:00:00Z',
    indexedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'mdl-009',
    externalId: 'tv-702345',
    name: 'Name Keychain Generator',
    localizedName: 'מחזיק מפתחות עם שם',
    description: 'Customizable name keychain. Add any text to create a personalized keychain.',
    localizedDescription: 'מחזיק מפתחות מותאם אישית עם שם. הוסיפו כל טקסט ליצירת מחזיק מפתחות אישי.',
    images: [
      { url: '/mock/models/keychain-1.jpg', alt: 'Name keychain', isThumbnail: true, cachedUrl: '/mock/models/keychain-1.jpg' },
    ],
    source: SOURCES.thingiverse,
    sourceUrl: 'https://www.thingiverse.com/thing:702345',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-gifts', 'cat-fashion'],
    tags: ['keychain', 'name', 'personalized', 'gift', 'custom', 'text'],
    popularityScore: 90,
    supportsEmbossedText: true,
    supportedMaterials: ['PLA', 'PETG', 'ABS', 'TPU'],
    defaultDimensions: { widthMm: 60, heightMm: 25, depthMm: 5 },
    minDimensions: { widthMm: 40, heightMm: 15, depthMm: 3 },
    maxDimensions: { widthMm: 100, heightMm: 40, depthMm: 8 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 15,
    printTimeMinutes: 30,
    createdAt: '2024-02-14T10:00:00Z',
    updatedAt: '2025-03-05T08:00:00Z',
    indexedAt: '2025-03-05T00:00:00Z',
  },
  {
    id: 'mdl-010',
    externalId: 'pr-445678',
    name: 'Phone Stand - Adjustable Angle',
    localizedName: 'מעמד טלפון - זווית מתכווננת',
    description: 'Adjustable angle phone stand compatible with all phone sizes. Folds flat for travel.',
    localizedDescription: 'מעמד טלפון בזווית מתכווננת, תואם לכל גדלי הטלפונים. מתקפל לנשיאה נוחה.',
    images: [
      { url: '/mock/models/phone-stand-1.jpg', alt: 'Adjustable phone stand', isThumbnail: true, cachedUrl: '/mock/models/phone-stand-1.jpg' },
    ],
    source: SOURCES.printables,
    sourceUrl: 'https://www.printables.com/model/445678',
    license: getLicense('CC-BY-SA-4.0'),
    categories: ['cat-gadgets'],
    tags: ['phone', 'stand', 'adjustable', 'portable', 'desk', 'holder'],
    popularityScore: 88,
    supportsEmbossedText: true,
    supportedMaterials: ['PLA', 'PETG'],
    defaultDimensions: { widthMm: 80, heightMm: 90, depthMm: 100 },
    minDimensions: { widthMm: 60, heightMm: 65, depthMm: 70 },
    maxDimensions: { widthMm: 120, heightMm: 130, depthMm: 150 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 22,
    printTimeMinutes: 75,
    createdAt: '2024-04-18T10:00:00Z',
    updatedAt: '2025-02-28T08:00:00Z',
    indexedAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'mdl-011',
    externalId: 'mmf-105567',
    name: 'Medieval Castle Dice Tower',
    localizedName: 'מגדל קוביות טירה מימי הביניים',
    description: 'Detailed medieval castle dice tower for tabletop gaming. Multiple levels ensure random rolls.',
    localizedDescription: 'מגדל קוביות בעיצוב טירה מפורט למשחקי שולחן. מספר קומות מבטיחות גלגול אקראי.',
    images: [
      { url: '/mock/models/dice-tower-1.jpg', alt: 'Castle dice tower', isThumbnail: true, cachedUrl: '/mock/models/dice-tower-1.jpg' },
    ],
    source: SOURCES.myminifactory,
    sourceUrl: 'https://www.myminifactory.com/object/105567',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-toys', 'cat-miniatures'],
    tags: ['dice', 'tower', 'castle', 'medieval', 'tabletop', 'DnD', 'gaming'],
    popularityScore: 74,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA', 'PETG'],
    defaultDimensions: { widthMm: 80, heightMm: 180, depthMm: 80 },
    minDimensions: { widthMm: 60, heightMm: 130, depthMm: 60 },
    maxDimensions: { widthMm: 120, heightMm: 260, depthMm: 120 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 48,
    printTimeMinutes: 420,
    createdAt: '2024-10-10T10:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z',
    indexedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'mdl-012',
    externalId: 'tv-812001',
    name: 'Honeycomb Shelf Bracket',
    localizedName: 'תומך מדף חלת דבש',
    description: 'Decorative honeycomb-pattern shelf bracket. Strong enough for light shelves.',
    localizedDescription: 'תומך מדף דקורטיבי בדוגמת חלת דבש. חזק מספיק למדפים קלים.',
    images: [
      { url: '/mock/models/shelf-bracket-1.jpg', alt: 'Honeycomb shelf bracket', isThumbnail: true, cachedUrl: '/mock/models/shelf-bracket-1.jpg' },
    ],
    source: SOURCES.thingiverse,
    sourceUrl: 'https://www.thingiverse.com/thing:812001',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-home-decor'],
    tags: ['shelf', 'bracket', 'honeycomb', 'wall', 'mount', 'decorative'],
    popularityScore: 65,
    supportsEmbossedText: false,
    supportedMaterials: ['PETG', 'ABS'],
    defaultDimensions: { widthMm: 150, heightMm: 150, depthMm: 20 },
    minDimensions: { widthMm: 100, heightMm: 100, depthMm: 15 },
    maxDimensions: { widthMm: 250, heightMm: 250, depthMm: 30 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 20,
    printTimeMinutes: 120,
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2025-02-05T08:00:00Z',
    indexedAt: '2025-02-10T00:00:00Z',
  },
  {
    id: 'mdl-013',
    externalId: 'pr-556789',
    name: 'Anatomical Heart Model',
    localizedName: 'מודל לב אנטומי',
    description: 'Detailed anatomical heart model for education. Can be split into two halves to show internal structure.',
    localizedDescription: 'מודל לב אנטומי מפורט ללמידה. ניתן לפיצול לשני חלקים להצגת המבנה הפנימי.',
    images: [
      { url: '/mock/models/heart-model-1.jpg', alt: 'Anatomical heart', isThumbnail: true, cachedUrl: '/mock/models/heart-model-1.jpg' },
    ],
    source: SOURCES.printables,
    sourceUrl: 'https://www.printables.com/model/556789',
    license: getLicense('CC-BY-SA-4.0'),
    categories: ['cat-education', 'cat-art'],
    tags: ['heart', 'anatomy', 'medical', 'education', 'science', 'biology'],
    popularityScore: 69,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA', 'PETG'],
    defaultDimensions: { widthMm: 100, heightMm: 120, depthMm: 80 },
    minDimensions: { widthMm: 60, heightMm: 70, depthMm: 50 },
    maxDimensions: { widthMm: 200, heightMm: 240, depthMm: 160 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 38,
    printTimeMinutes: 200,
    createdAt: '2024-08-08T10:00:00Z',
    updatedAt: '2025-01-28T08:00:00Z',
    indexedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'mdl-014',
    externalId: 'mmf-120987',
    name: 'Voronoi Lampshade',
    localizedName: 'אהיל ורונוי',
    description: 'Stunning Voronoi-pattern lampshade that creates beautiful light patterns on walls.',
    localizedDescription: 'אהיל מרהיב בדוגמת ורונוי שיוצר דפוסי אור יפהפיים על הקירות.',
    images: [
      { url: '/mock/models/voronoi-lamp-1.jpg', alt: 'Voronoi lampshade lit', isThumbnail: true, cachedUrl: '/mock/models/voronoi-lamp-1.jpg' },
    ],
    source: SOURCES.myminifactory,
    sourceUrl: 'https://www.myminifactory.com/object/120987',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-home-decor', 'cat-art'],
    tags: ['lamp', 'voronoi', 'lampshade', 'lighting', 'decorative', 'art'],
    popularityScore: 82,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA'],
    defaultDimensions: { widthMm: 180, heightMm: 200, depthMm: 180 },
    minDimensions: { widthMm: 120, heightMm: 130, depthMm: 120 },
    maxDimensions: { widthMm: 280, heightMm: 300, depthMm: 280 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 55,
    printTimeMinutes: 480,
    createdAt: '2024-06-30T10:00:00Z',
    updatedAt: '2025-02-12T08:00:00Z',
    indexedAt: '2025-02-15T00:00:00Z',
  },
  {
    id: 'mdl-015',
    externalId: 'tv-890012',
    name: 'Cable Clip Organizer Set',
    localizedName: 'סט קליפסים לכבלים',
    description: 'Set of adhesive cable management clips in various sizes. Keep your desk and cables tidy.',
    localizedDescription: 'סט קליפסים לניהול כבלים בגדלים שונים. שמרו על שולחן העבודה והכבלים מסודרים.',
    images: [
      { url: '/mock/models/cable-clips-1.jpg', alt: 'Cable clip set', isThumbnail: true, cachedUrl: '/mock/models/cable-clips-1.jpg' },
    ],
    source: SOURCES.thingiverse,
    sourceUrl: 'https://www.thingiverse.com/thing:890012',
    license: getLicense('CC0-1.0'),
    categories: ['cat-gadgets', 'cat-office'],
    tags: ['cable', 'clip', 'organizer', 'desk', 'tidy', 'management'],
    popularityScore: 79,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA', 'PETG', 'TPU'],
    defaultDimensions: { widthMm: 30, heightMm: 15, depthMm: 20 },
    minDimensions: { widthMm: 20, heightMm: 10, depthMm: 15 },
    maxDimensions: { widthMm: 50, heightMm: 25, depthMm: 35 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 12,
    printTimeMinutes: 20,
    createdAt: '2024-11-15T10:00:00Z',
    updatedAt: '2025-02-25T08:00:00Z',
    indexedAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'mdl-016',
    externalId: 'pr-667890',
    name: 'Geometric Pendant Necklace',
    localizedName: 'שרשרת תליון גיאומטרי',
    description: 'Lightweight geometric pendant for necklace. Modern design suitable for everyday wear.',
    localizedDescription: 'תליון גיאומטרי קל משקל לשרשרת. עיצוב מודרני מתאים לשימוש יומיומי.',
    images: [
      { url: '/mock/models/pendant-1.jpg', alt: 'Geometric pendant', isThumbnail: true, cachedUrl: '/mock/models/pendant-1.jpg' },
    ],
    source: SOURCES.printables,
    sourceUrl: 'https://www.printables.com/model/667890',
    license: getLicense('CC-BY-4.0'),
    categories: ['cat-fashion'],
    tags: ['jewelry', 'pendant', 'necklace', 'geometric', 'fashion', 'wearable'],
    popularityScore: 63,
    supportsEmbossedText: false,
    supportedMaterials: ['PLA', 'Resin'],
    defaultDimensions: { widthMm: 35, heightMm: 45, depthMm: 5 },
    minDimensions: { widthMm: 20, heightMm: 25, depthMm: 3 },
    maxDimensions: { widthMm: 50, heightMm: 65, depthMm: 8 },
    previewAvailable: false,
    cachedAssetState: 'thumbnails_cached',
    availability: 'available',
    estimatedBasePrice: 18,
    printTimeMinutes: 45,
    createdAt: '2024-09-20T10:00:00Z',
    updatedAt: '2025-01-18T08:00:00Z',
    indexedAt: '2025-02-01T00:00:00Z',
  },
];
